version: 3.0.{build}
os: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\SolutionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  DNX_FEED: https://www.nuget.org/api/v2
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: >-
    nuget restore

    dnvm upgrade

    dnu restore
after_build:
 - ps: dnu publish
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: Rnwood.SmtpServer\bin\Debug\*
  name: Rnwood.SmtpServer-{version}
  type: zip
- path: 'output/**/*'
  name: Rnwood.Smtp4dev-{version}
  type: zip
