# escape=`
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 AS final
COPY out /app
EXPOSE 80
EXPOSE 25
EXPOSE 143
ENV ASPNETCORE_HTTP_PORTS 80
ENV SERVEROPTIONS__URLS http://localhost:80
VOLUME c:\smtp4dev
WORKDIR c:\
ENTRYPOINT ["/app/Rnwood.Smtp4dev.exe"]