FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
RUN apt update
RUN apt install -y curl
COPY out /app
RUN mkdir -p /smtp4dev && chown -R app:app /smtp4dev
VOLUME ["/smtp4dev"]
WORKDIR /
ENV XDG_CONFIG_HOME /
ENV ASPNETCORE_HTTP_PORTS 80
ENV SERVEROPTIONS__URLS http://*:80
ENV DOTNET_USE_POLLING_FILE_WATCHER true
EXPOSE 80
EXPOSE 25
EXPOSE 143
EXPOSE 110
ENTRYPOINT ["dotnet", "/app/Rnwood.Smtp4dev.dll"]
