name: Cleanup Releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 10
          delete_tag_pattern: -ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
